apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: callme-service
build:
  artifacts:
    - image: vgrente/callme-service
      buildpacks:
        builder: dashaun/java-native-builder-arm64:7.41.0
        env:
          - BP_BOOT_NATIVE_IMAGE=true
deploy:
  kubectl:
    manifests:
      - k8s/ksvc.yaml
profiles:
  - name: jib
    build:
      artifacts:
        - image: vgrente/callme-service
          jib: {}
