apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pipeline-role
rules:
  - apiGroups: ["extensions", "apps", "serving.knative.dev",""]
    resources: ["services", "deployments", "pods","pvc","job"]
    verbs: ["get", "create", "update", "patch", "list", "delete"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pipeline-role-binding
subjects:
  - kind: ServiceAccount
    name: buildpacks-service-account
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pipeline-role

